name: zarr-proxy
channels:
  - conda-forge
  - nodefaults
dependencies:
  - aiohttp
  - fastapi
  - fsspec
  - httpx
  - mangum
  - pytest
  - requests
  - uvicorn
  - zarr
  - pip
  - pydantic >= 2.0
  - pydantic-settings >= 2.0
  - pytest-cov
