version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "zarr-proxy"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7yvk77i1v3iz"
s3_prefix = "zarr-proxy"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
