AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Zarr Proxy on Lambda
# Globals:
#   Function:
#     Timeout: 3

Resources:
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: zarr-proxy
      CodeUri: ./
      Handler: zarr_proxy.main.handler
      Runtime: python3.9
      Events:
        Root:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        NonRoot:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  Api:
    Description: 'API Gateway endpoint URL for Prod stage for App function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'
