name: aws-lambda-deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_USER: ${{ secrets.AWS_USER }}
  SAM_CLI_TELEMETRY: 0 # Disable SAM CLI telemetry

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: deployments/aws

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Set up Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install aws-cdk
        run: |
          yarn install

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      # - uses: aws-actions/setup-sam@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Booststrap CDK
        run: |
          yarn cdk bootstrap

      - name: Print CloudFormation template
        run: |
          yarn cdk synth

      #   # Build inside Docker containers
      # - name: Build lambda function
      #   run: sam build --use-container
      # # Prevent prompts and failure when the stack is unchanged
      # - name: Deploy to AWS Lambda
      #   run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
